---
title: "Progress Update"
author: Xiang Zhu
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

[sequence-conserved enhancer-like elements]: https://doi.org/10.1101/2022.08.19.504589
[RSS-NET]: https://doi.org/10.1038/s41467-021-22588-0 
[RSS-E]: https://doi.org/10.1038/s41467-018-06805-x
[RSS likelihood]: https://doi.org/10.1214/17-aoas1046

- 07/31/2023: Xiang received the [Penn State Clinical and Translational Science Institute](http://ctsi.psu.edu/)
Bridges to Translation Pilot Grant as the Lead PI to incorporate single-cell genomics and multi-ancestry GWAS
into the [RSS likelihood][] framework, with a special focus on genetics of substance use in diverse human populations.
*Penn State Today* published a [press release](https://www.psu.edu/news/clinical-and-translational-science-institute/story/penn-state-ctsi-announces-seven-bridges/).

- 05/12/2023: Xiang presented the [RSS likelihood][] and its various applications in human genetics
at the Department of Biostatistics and Epidemiology, University of Massachusetts, Amherst, MA.

- 04/28/2023: Xiang presented the extension of [RSS-NET][] to analyze
[sequence-conserved enhancer-like elements][]
at the Program in Computational Biology, University of Chicago, Chicago, IL.

- 04/26/2023: Xiang presented the [RSS likelihood][] and its various applications in human genetics
at the Department of Mathematics, Statistics and Computer Science, University of Illinois at Chicago, Chicago, IL.

- 04/20/2023: Xiang presented the [RSS likelihood][] and its various applications in human genetics
at the Department of Statistics, University of Florida, Gainesville, FL.

- 04/14/2023: Xiang presented the extension of [RSS-NET][] to analyze
[sequence-conserved enhancer-like elements][]
at the Department of Biostatistics, University of Florida, Gainesville, FL.

- 03/01/2023: Xiang presented the extension of [RSS-NET][] to analyze
[sequence-conserved enhancer-like elements][]
at the Center for Computational Biology and Bioinformatics,
Pennsylvania State University, University Park, PA.

- 02/03/2023: Xiang's recent work on the genetics of cardiovascular health in diverse human populations
and the ongoing effort to extend RSS methods to multi-ancestry GWAS were featured as the
[Editor's Picks in *Penn State Today*](https://www.psu.edu/news/eberly-college-science/story/improving-heart-health-diversifying-genetic-data/).

- 12/18/2022: Xiang presented [RSS-NET][] and its extensions to analyze
[H3K27ac HiChIP networks](https://doi.org/10.1073/pnas.2115601119) and
[sequence-conserved enhancer-like elements]
at the 2022 CMStatistics, London, UK.

- 09/14/2022: Xiang presented the [RSS likelihood][] and its various applications in human genetics
at the Department of Statistics, University of Nebraska-Lincoln, Lincoln, NE.

- 08/19/2022: Xiang extended [RSS-NET][] to analyze
[sequence-conserved enhancer-like elements][], which was posted on *bioRxiv*.

- 08/04/2022: Xiang applied [RSS-NET][] to identify relevant tissues and cell types for
five lipid traits based on the latest [GWAS results from GLGC](https://doi.org/10.1038/s41586-021-04064-3).
This [application](https://doi.org/10.1016/j.ajhg.2022.06.012) was published in *American Journal of Human Genetics*.

- 08/01/2022: Xiang applied [RSS-E][] to prioritize pathways and genes for coronary artery disease
based on the latest [GWAS results from MVP](https://doi.org/10.1038/s41591-022-01891-3).
This [application](https://doi.org/10.1038/s41591-022-01891-3) was published in *Nature Medicine*.

- 05/18/2022: Xiang received the [Penn State Social Science Research Institute Consortium on Substance Use and Addiction](https://csua.ssri.psu.edu/)
Seed Grant as the Lead PI to incorporate single-cell genomics and multi-ancestry GWAS into the [RSS likelihood][] framework,
with a special focus on genetics of tobacco use in diverse human populations.

- 05/02/2022: Xiang presented [RSS-NET][] at the Department of Statistics, 
University of Missouri, Columbia, MO.

- 03/30/2022: Xiang received the [Penn State Institute for Computational and Data Sciences](https://www.icds.psu.edu/)
Seed Grant as the Lead PI to incorporate single-cell genomics and multi-ancestry GWAS into the [RSS likelihood][] framework,
with a special focus on genetics of cardiometabolic diseases in diverse human populations.
*Penn State Today* published a [press release](https://www.psu.edu/news/institute-computational-and-data-sciences/story/seed-grants-fund-projects-tackle-huge-scientific/).

- 01/04/2022: Xiang extended [RSS-NET][] to analyze regulatory networks derived
from H3K27ac HiChIP experiments. This [extension](https://doi.org/10.1073/pnas.2115601119)
was published in *Proceedings of the National Academy of Sciences*. 

- 06/29/2021: Xiang presented [RSS-NET][] at the 2021 Virtual ISBA World Meeting. 

- 05/14/2021: [RSS-NET][] was published in *Nature Communications*.

- 05/07/2021: Xiang presented [RSS-NET][] at the Program in Computational Biology,
University of Chicago, Chicago, IL.

- 04/15/2021: Xiang presented [RSS-NET][] at the Division of Biostatistics and
Bioinformatics, Department of Public Health Sciences,
Penn State College of Medicine, Hershey, PA.

- 04/14/2021: Xiang presented [RSS-NET][] at the 2021 Virtual CSHL
Probabilistic Modeling in Genomics Meeting. 

- 03/03/2021: [RSS-NET][] was accepted by *Nature Communications*.

- 11/04/2020: Xiang presented [RSS-NET][] at the 2020 Virtual CSHL
Biological Data Science Meeting. 

- 08/05/2020: Xiang presented [RSS-NET][] at the 2020 Virtual JSM.

- 04/28/2020: Xiang presented [RSS-NET][] at the Department of Statistics,
Stanford University, Stanford, CA.

- 03/14/2020: Xiang posted [RSS-NET][] on *bioRxiv*.

- 02/10/2020: Xiang presented [RSS-NET][] at the Department of Biostatistics and
Bioinformatics, Rollins School of Public Health, Emory University, Atlanta, GA.

- 01/23/2020: Xiang presented [RSS-NET][] at the Department of Statistics and
Huck Institutes of the Life Sciences, Pennsylvania State University,
University Park, PA.

- 01/15/2020: Xiang presented [RSS-NET][] at the Department of Statistics,
Wharton School, University of Pennsylvania, Philadelphia, PA.

- 03/27/2019: [RSS-E][] was recommended in
[F1000Prime](https://doi.org/10.3410/f.734261365.793558023)
by F1000 Faculty Member
[Jason Flannick](https://f1000.com/prime/thefaculty/member/499999771097550974).

- 01/10/2019: The Research Computing Center at University of Chicago wrote an
[article](https://rcc.uchicago.edu/about-rcc/news-features/new-statistical-method-gives-second-life-gwas-data)
on [RSS likelihood][] and [RSS-E][].

- 10/19/2018: [RSS-E][] was published in *Nature Communications*.

- 10/09/2018: Xiang presented [RSS-E][] at the MVP/ERIC/Assimes Group Meeting,
Stanford University, Stanford, CA.

- 09/29/2018: [RSS-E][] was accepted by *Nature Communications*.

- 10/19/2017: Xiang presented [RSS-E][] at the 2017 ASHG, Orlando, FL.

- 10/05/2017: [RSS likelihood][] was published in *Annals of Applied Statistics*.

- 08/03/2017: Xiang presented [RSS-E][] at the 2017 JSM, Baltimore, MD.
This work won an [American Statistical Association Student Paper Award](https://stat.uchicago.edu/academics/graduate-programs/graduate-student-resources/academic-life/student-awards/#collapse13).

- 07/07/2017: Xiang posted [RSS-E][] on *bioRxiv*.

- 06/30/2017: Xiang presented [RSS likelihood][] and [RSS-E][]
at Dissertation Presentation and Defense, Department of Statistics,
University of Chicago, Chicago, IL.

- 06/28/2017: Xiang presented [RSS-E][] at the
2017 ICSA Applied Statistics Symposium, Chicago, IL.

- 05/02/2017: Xiang presented [RSS-E][] at the Mind Bytes 2017,
University of Chicago, Chicago, IL. This work won the [Mind Bytes Award for Big-Data Research](https://mindbytes.uchicago.edu/2017/callforposters.php#tab8).

- 04/04/2017: [RSS likelihood][] was accepted by *Annals of Applied Statistics*.

- 02/22/2017: Xiang presented [RSS likelihood][] at
the Department of Statistics, Stanford University, Stanford, CA.

- 01/11/2017: Xiang presented [RSS-E][] at the Department of Human Genetics,
University of Chicago, Chicago, IL.

- 12/02/2016: Xiang presented [RSS likelihood][] as part of a GWAS tutorial
at the Program in Computational Biology, University of Chicago, Chicago, IL.

- 10/20/2016: Xiang presented [RSS-E][] at the 2016 ASHG, Vancouver, BC, Canada.

- 08/23/2016: [Stephen Hsu](https://pa.msu.edu/profile/hsu/) wrote a
[blog](https://infoproc.blogspot.com/2016/08/bayesian-large-scale-multiple.html)
about [RSS likelihood][].

- 07/31/2016: Xiang presented [RSS likelihood][] at the 2016 JSM, Chicago, IL.

- 03/04/2016: Xiang posted [RSS likelihood][] on *bioRxiv*. 

- 03/04/2016: Xiang presented [RSS-E][] at the Program in Computational Biology,
University of Chicago, Chicago, IL.

- 11/11/2015: Xiang presented [RSS likelihood][] at the Dissertation Proposal
Presentation, Department of Statistics, University of Chicago, Chicago, IL.

- 10/27/2015: Xiang presented [RSS-E][] at the Mind Bytes 2015,
University of Chicago, Chicago, IL.

- 10/15/2015: Xiang presented [RSS-E][] at the 2015 ProbGen,
Cold Spring Harbor Laboratory, Cold Spring Harbor, NY.

- 10/09/2015: Xiang presented [RSS likelihood][] at the 2015 ASHG, Baltimore, MD.

- 05/05/2015: Xiang received the inaugural [David Wallace Award for Applied Statistics](https://stat.uchicago.edu/academics/graduate-programs/graduate-student-resources/academic-life/student-awards/#collapse22) for the work on [RSS likelihood][]. 

- 02/27/2015: Xiang presented [RSS likelihood][] at the Program in Computational Biology,
University of Chicago, Chicago, IL.
