---
title: "MCMC Installation"
author: Xiang Zhu
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

[This page](setup_mcmc.html) shows how to install the
[Monte Carlo Markov chain (MCMC)](https://en.wikipedia.org/wiki/Markov_chain_Monte_Carlo)
scripts in [`rss/src/`](https://github.com/stephenslab/rss/tree/master/src).
In a standard computing environment with internet connection,
the installation time is typically less than 10 minutes.

[`git`]: https://git-scm.com/downloads
[`rss`]: https://github.com/stephenslab/rss

## Step-by-step guide

### 0. Install [`git`][] (optional)

To simplify Step 1 below, you may consider
installing [`git`][] in your computing environment
(if it is not available there).
Please see this [excellent tutorial](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
on installing [`git`][].

Please note that RSS software does not depend on [`git`][].
You can complete Step 1 without installing [`git`][].

### 1. Clone [`rss`][] repository

With [`git`][] installed, you can easily clone
[`rss`][] by running the following command in Terminal.

```zsh
git clone git@github.com:stephenslab/rss.git
```

Without [`git`][], you can manually download [`rss`][] as follows.

```zsh
wget https://github.com/stephenslab/rss/archive/master.zip
unzip master.zip
rm master.zip
mv rss-master rss
```

### 2. Download external packages

Download and install the [`lightspeed`](http://research.microsoft.com/en-us/um/people/minka/software/lightspeed/)
MATLAB toolbox (author: Tom Minka).

```zsh
cd rss/src
wget http://ftp.research.microsoft.com/downloads/db1653f0-1308-4b45-b358-d8e1011385a0/lightspeed.zip
unzip lightspeed.zip
rm lightspeed.zip
cd lightspeed/
matlab -nodisplay < install_lightspeed.m
```

Download and install the [`lapack`](http://www.mathworks.com/matlabcentral/fileexchange/16777-lapack)
MATLAB package (author: Tim Toolan).

```zsh
cd rss/src
unzip lapack.zip
rm lapackhelp.m lapack.zip license.txt
```

Note that if an appropriately compiled version of `lapack.c`
does not exist, this package will ask whether to build one.  

Download the [`progress`](http://www.mathworks.com/matlabcentral/fileexchange/8564-progress)
MATLAB package (author: Martinho Marta-Almeida).

```zsh
unzip progress.zip
rm progress.zip license.txt 
```

All downloaded files must be placed under `rss/src`.

```zsh
-rw-rw-r-- 1 xiangzhu xiangzhu   5261 2015-11-11 08:46 calc_posterior_bvsr.m
-rw-rw-r-- 1 xiangzhu xiangzhu    972 2015-11-11 08:46 compute_pve.m
-rw-rw-r-- 1 xiangzhu xiangzhu  86772 2015-11-11 12:01 lapack.c
-rw-rw-r-- 1 xiangzhu xiangzhu   5927 2015-11-11 12:01 lapack.m
-rwxrwxr-x 1 xiangzhu xiangzhu 120123 2015-11-11 12:12 lapack.mexa64
drwx------ 6 xiangzhu xiangzhu  32768 2015-11-11 11:54 lightspeed
-rw-rw-r-- 1 xiangzhu xiangzhu   2573 2015-11-11 12:01 progress.m
-rw-rw-r-- 1 xiangzhu xiangzhu   4402 2015-11-11 08:46 propose_gamma.m
-rw-rw-r-- 1 xiangzhu xiangzhu  11629 2015-11-11 08:46 rss_ash.m
-rw-rw-r-- 1 xiangzhu xiangzhu  22182 2015-11-11 08:46 rss_bslmm.m
-rw-rw-r-- 1 xiangzhu xiangzhu   8363 2015-11-11 08:46 rss_bvsr.m
-rw-rw-r-- 1 xiangzhu xiangzhu  11348 2015-11-11 08:46 update_betatilde.m
-rw-rw-r-- 1 xiangzhu xiangzhu   4796 2015-11-11 08:46 update_bz.m
-rw-rw-r-- 1 xiangzhu xiangzhu  17205 2015-11-11 08:46 update_zlabel.m
```

## Computing environment

Please note that RSS MCMC components have only been
extensively tested in the following environments:

- version 8.4.0.150421 (R2014b) of MATLAB for 64-bit Linux

- version 8.2.0.701 (R2013b) of MATLAB for 64-bit Linux

- version 8.1.0.604 (R2013a) of MATLAB for 64-bit Linux

If you have any trouble installing RSS-NET,
please open an [issue](https://github.com/SUwonglab/rss-net/issues)
or email me (`xiangzhu[at]uchicago[and/or]stanford.edu`).
To help me better understand your problems,
please provide details of your computing environment.

